{% set name = "funcx-common" %}
{% set version = "0.0.25" %}

package:
  name: funcx-common-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/funcx-common-{{ version }}.tar.gz
  sha256: 006850a91d77cc060238b8afd70782c8a6524cdfbae800307b374985b6f8f8de

build:
  number: 2

outputs:

  - name: funcx-common
    script: build-core.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - pydantic >=1,<2
      run_constrained:
        - moto <5
        - redis-py >=3.5.3,<5
        - boto3 >=1.19.0
    test:
      imports:
        - funcx_common
      commands:
        - pip check
      requires:
        - pip


  - name: funcx-common-moto
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('funcx-common', exact=True) }}
        - moto
    test:
      imports:
        - funcx_common
      commands:
        - pip check
      requires:
        - pip


  - name: funcx-common-boto3
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('funcx-common', exact=True) }}
        - boto3
    test:
      imports:
        - funcx_common
      commands:
        - pip check
      requires:
        - pip

  - name: funcx-common-redis
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('funcx-common', exact=True) }}
        - redis-py
    test:
      imports:
        - funcx_common
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/funcX-faas/funcx-common
  summary: A common core repo for tools shared across multiple funcx python projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
